predict:
  SEED: 11
  comments_linux:
    count_video: 2
    limit: 10
    maxResults: 100
    nextPageToken: ''
    query: линукс
  comments_windows:
    count_video: 2
    limit: 10
    maxResults: 100
    nextPageToken: ''
    query: виндовс
  dir_folder: /home/primera7790/ml_projects/linux_or_windows
  model_vec: vector_tfidf
  name_file: data/prediction.csv
  num_top: 5
  stopwords: russian
  version_model_dt: 0
  version_model_lr: 2
  version_model_rf: 14
  version_vec: 16
train:
  SEED: 11
  clf: 2
  comments_linux:
    count_video: 10
    limit: 30
    maxResults: 100
    nextPageToken: ''
    query: линукс
  comments_windows:
    count_video: 10
    limit: 30
    maxResults: 100
    nextPageToken: ''
    query: виндовс
  cross_val:
    test_size: 0.3
  dir_folder: /home/primera7790/ml_projects/linux_or_windows
  model_name:
  - model_lr
  - model_dt
  - model_rf
  model_vec: vector_tfidf
  name_experiment: linux_or_windows
  stopwords: russian
  tf_model:
    max_features: 300
